### ISSUE TITLE
cargo agent result: where are the attribute names?

### ISSUE THREAD

**Issue by cleemansen** [movestore/MorningRep_AttrPlots#1]
In the setting of this app you mention the cargo-agent-view of the prev. app:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/868171/132464933-41dd9047-a616-4e54-b17c-73579911bd3b.png">

I can not find "attributes" in this cargo agent view:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/868171/132465040-3a583dde-69b2-4f8d-b4d3-c6d32a92a812.png">

- Perhaps "variable names" is the right? 
- Should we change the note for this setting or 
- the label in the cargo-agent-view?

**Comment by andreakoelzsch** [comment]
name in this appspec has been adapted long ago, sorry for not having seen this issue before
